version: '2.1'

services:
  go_coyote:
    image: go_coyote
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
      - "8000:8000"
    security_opt:
      - "seccomp:unconfined"
    command: /go/bin/dlv debug --headless --log --listen=:8000 --api-version=2
    volumes:
      - .:/go/src/app

  mux:
    image: benst/go-mux:latest
